default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: zaikoban_development
  username: postgres
  password: password
  host: db
  port: 5432

test:
  <<: *default
  database: zaikoban_test
  username: postgres
  password: password
  host: db
  port: 5432

production:
  <<: *default
  database: zaikoban_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
